WALLS = True
SPEED = 0.1  # Larger numbers are slower.
WIDTH = 200
HEIGHT = 50
STARTING_TAIL_LENGTH = 50
LOCALHOST_ONLY = True
INFINITE_AMMO = False
AMMO_RARITY = 400  # 1 in this many blocks is ammo.
MINES = True
MINE_RARITY = 500
