#!/usr/bin/python
"""App launcher to open Nuke Snake in a new Terminal window."""

import os
import subprocess
import syslog

syslog.syslog(
    syslog.LOG_NOTICE,
    'Starting NukeSnake from Python wrapper script %s in app.' % __file__)

py_src_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'Contents', 'Resources'))

launcher_abspath = os.path.join(py_src_dir, 'launcher.py')
syslog.syslog(
    syslog.LOG_DEBUG,
    'Opening Terminal for: %s' % launcher_abspath)
subprocess.call(['open', '-a', 'Terminal', launcher_abspath])
