#!/usr/bin/python
"""App launcher to start server and client for Nuke Snake."""

import os
import subprocess
import syslog

syslog.syslog(
    syslog.LOG_NOTICE,
    'Starting NukeSnake from Python wrapper script %s in app.' % __file__)

py_src_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'Contents', 'Resources'))

for runner in ('client.py', 'network.py'):
  runner_abspath = os.path.join(py_src_dir, runner)
  syslog.syslog(
      syslog.LOG_DEBUG,
      'Opening Terminal for: %s' % runner_abspath)
  subprocess.call(['open', '-a', 'Terminal', runner_abspath])
